name: PR
on:
  pull_request:
    branches:
      - main
jobs:
  deploy:
    name: PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler: 'latest'
      - run: npm install -g @shopify/cli @shopify/theme
      - run: npm install
      - run: npm run styles & npm run scripts